### ISSUE TITLE
Support for OS X

### ISSUE THREAD

**Issue by AlickH** [anlar/prismriver#3]
when I execute it, it appears:

>~/prismriver-lyrics-0.3.0/prismriver-lunasa.py 
Traceback (most recent call last):
  File "/Users/SID/prismriver-lyrics-0.3.0/prismriver-lunasa.py", line 6, in <module>
    gui.run()
  File "/Users/SID/prismriver-lyrics-0.3.0/prismriver/qt/gui.py", line 16, in run
    MainController(search_config, params.artist, params.title, params.mpris, params.connect, params.tray)
  File "/Users/SID/prismriver-lyrics-0.3.0/prismriver/qt/controller.py", line 30, in __init__
    self.start_app(default_artist, default_title, default_player, connect_to_player, tray_action)
  File "/Users/SID/prismriver-lyrics-0.3.0/prismriver/qt/controller.py", line 37, in start_app
    self.main_window = MainWindow()
  File "/Users/SID/prismriver-lyrics-0.3.0/prismriver/window.py", line 12, in __init__
    uic.loadUi('prismriver/qt/window.ui', self)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/uic/__init__.py", line 226, in loadUi
    return DynamicUILoader(package).loadUi(uifile, baseinstance, resource_suffix)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/uic/Loader/loader.py", line 72, in loadUi
    return self.parse(filename, resource_suffix, basedir)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyQt5/uic/uiparser.py", line 992, in parse
    document = parse(filename)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xml/etree/ElementTree.py", line 1184, in parse
    tree.parse(source, parser)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/xml/etree/ElementTree.py", line 585, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'prismriver/qt/window.ui'

how can I solve it? Thanks!

**Comment by anlar** [comment]
Hi,

Could you try to launch it from project directory itself? First 'cd prismriver-lyrics-0.3.0' and then execute './prismriver-lunasa.py'.

**Comment by AlickH** [comment]
However there is another problem = =

> Traceback (most recent call last):
>   File "/Users/SID/Desktop/prismriver-lyrics-0.3.0/prismriver-lunasa.py", line 6, in <module>
>     gui.run()
>   File "/Users/SID/Desktop/prismriver-lyrics-0.3.0/prismriver/qt/gui.py", line 16, in run
>     MainController(search_config, params.artist, params.title, params.mpris, params.connect, params.tray)
>   File "/Users/SID/Desktop/prismriver-lyrics-0.3.0/prismriver/qt/controller.py", line 30, in **init**
>     self.start_app(default_artist, default_title, default_player, connect_to_player, tray_action)
>   File "/Users/SID/Desktop/prismriver-lyrics-0.3.0/prismriver/qt/controller.py", line 37, in start_app
>     self.main_window = MainWindow()
>   File "/Users/SID/Desktop/prismriver-lyrics-0.3.0/prismriver/qt/window.py", line 15, in **init**
>     self.init_table()
>   File "/Users/SID/Desktop/prismriver-lyrics-0.3.0/prismriver/qt/window.py", line 44, in init_table
>     self.lyrics_table_model.layoutChanged.connect(self.update_lyric_pane)
> TypeError: decorated slot has no signature compatible with layoutChanged(QList<QPersistentModelIndex>,QAbstractItemModel::LayoutChangeHint)

sad😂

**Comment by anlar** [comment]
It seems that they've added strict validation to pyqt5.6: http://pyqt.sourceforge.net/Docs/PyQt5/incompatibilities.html#pyqt-v5-6 which I haven't encountered yet and pyqtSlot annotations here are not especially correct. I'll commit fix today or tomorrow. And if you need it before you could just remove from your copy all @pyqtSlot strings from window.py and controller.py files.

**Comment by anlar** [comment]
Try latest version from master - now it should work with latest pyqt5.

**Comment by AlickH** [comment]
Thanks for your update, but new problem appears TAT

> Traceback (most recent call last):
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver-gui.py", line 3, in <module>
>     from prismriver.qt import gui
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/qt/gui.py", line 23, in <module>
>     from prismriver.qt.controller import MainController
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/qt/controller.py", line 6, in <module>
>     from prismriver import main, util, mpris
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/mpris.py", line 20
>     except dbus.exceptions.DBusException:
>          ^
> SyntaxError: invalid syntax

BTW, I'm using OS X, so are these problems relevant to the OS?

**Comment by anlar** [comment]
There shouldn't be any OS X specific problems in general, I've just never tried to use it there so can only fix things if someone report them.

For dbus error it seems that it won't work properly on OS X. Could you please try to replace `mpris.py` with the following content:

```
class MprisConnector(object):
    def __init__(self):
        super().__init__()

    def get_players(self):
        pass

    def get_player(self, name):
        pass

    def connect(self, player):
        pass

    def get_meta(self):
        pass

class MprisPlayer(object):
    def __init__(self, name, identity):
        super().__init__()

        self.name = name
        self.identity = identity

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__


class MprisConnectionException(Exception):
    pass
```

It should disable MPRIS integration (which won't work anyway, I think).

**Comment by AlickH** [comment]
Finally it appears main window, but after these, it crashed = = and no search result appears in application window

![pic](https://i.imgur.com/tBu5x1P.png)

> 2016-11-09 23:50:27,081 INFO [main] Search lyrics on "TouhouWiki" [touhouwiki]...
> 2016-11-09 23:50:27,081 INFO [main] Search lyrics on "J-Lyric" [jlyric]...
> 2016-11-09 23:50:27,082 INFO [main] Search lyrics on "KGet" [kget]...
> 2016-11-09 23:50:27,085 INFO [main] Search lyrics on "UtaTen" [utaten]...
> 2016-11-09 23:50:27,085 INFO [main] Search lyrics on "Uta-Net" [utanet]...
> 2016-11-09 23:50:27,097 INFO [main] Search lyrics on "UtaMap" [utamap]...
> 2016-11-09 23:50:27,114 INFO [main] Search lyrics on "Amalgama" [amalgama]...
> 2016-11-09 23:50:27,126 INFO [main] Search lyrics on "Kasi-Time" [kasitime]...
> 2016-11-09 23:50:27,134 INFO [main] Found song info on "UtaTen" [utaten], 49.3 ms
> 2016-11-09 23:50:27,134 INFO [main] Search lyrics on "Bandcamp" [bandcamp]...
> 2016-11-09 23:50:27,147 INFO [main] Search lyrics on "Encyclopaedia Metallum" [metallum]...
> 2016-11-09 23:50:27,147 INFO [main] Search lyrics on "KashiNavi" [kashinavi]...
> 2016-11-09 23:50:27,171 INFO [main] Found song info on "J-Lyric" [jlyric], 90.2 ms
> 2016-11-09 23:50:27,177 INFO [main] Search lyrics on "LyricWiki" [lyricwiki]...
> 2016-11-09 23:50:27,189 INFO [main] Nothing was found on "Encyclopaedia Metallum" [metallum], 41.5 ms
> 2016-11-09 23:50:27,191 INFO [main] Nothing was found on "Bandcamp" [bandcamp], 44.2 ms
> 2016-11-09 23:50:27,192 INFO [main] Search lyrics on "SonicHits" [sonichits]...
> 2016-11-09 23:50:27,192 INFO [main] Search lyrics on "J-Lyrics.ru" [jlyricsru]...
> 2016-11-09 23:50:27,193 INFO [main] Found song info on "SonicHits" [sonichits], 0.9 ms
> 2016-11-09 23:50:27,193 INFO [main] Search lyrics on "Dark Lyrics" [darklyrics]...
> 2016-11-09 23:50:27,202 INFO [main] Nothing was found on "J-Lyrics.ru" [jlyricsru], 9.4 ms
> 2016-11-09 23:50:27,208 INFO [main] Search lyrics on "ShowMeLyrics" [showmelyrics]...
> 2016-11-09 23:50:27,209 INFO [main] Nothing was found on "Dark Lyrics" [darklyrics], 16.4 ms
> 2016-11-09 23:50:27,210 INFO [main] Search lyrics on "Musixmatch" [musixmatch]...
> 2016-11-09 23:50:27,212 INFO [main] Search lyrics on "Sing365" [sing365]...
> 2016-11-09 23:50:27,213 INFO [main] Search lyrics on "AZLyrics" [azlyrics]...
> 2016-11-09 23:50:27,240 INFO [main] Search lyrics on "Megalyrics" [megalyrics]...
> 2016-11-09 23:50:27,266 ERROR [main] Failed to get info from "ShowMeLyrics" [showmelyrics]
> Traceback (most recent call last):
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/main.py", line 224, in do_search
>     song = plugin.search_song(artist, title)
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/plugin/showmelyrics.py", line 35, in search_song
>     for elem in inner_lyrics_pane.findAll('p', recursive=False):
> AttributeError: 'NoneType' object has no attribute 'findAll'
> 2016-11-09 23:50:27,322 ERROR [main] Failed to get info from "AZLyrics" [azlyrics]
> Traceback (most recent call last):
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/main.py", line 224, in do_search
>     song = plugin.search_song(artist, title)
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/plugin/azlyrics.py", line 37, in search_song
>     lyric = self.parse_verse_block(lyric_pane)
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/plugin/common.py", line 187, in parse_verse_block
>     for elem in verse_block.childGenerator():
> AttributeError: 'NoneType' object has no attribute 'childGenerator'
> 2016-11-09 23:50:27,329 INFO [main] Search lyrics on "LyricsMania" [lyricsmania]...
> 2016-11-09 23:50:27,382 INFO [main] Search lyrics on "MetroLyrics" [metrolyrics]...
> 2016-11-09 23:50:27,385 INFO [main] Found song info on "Musixmatch" [musixmatch], 172.6 ms
> 2016-11-09 23:50:27,390 INFO [main] Found song info on "Megalyrics" [megalyrics], 149.8 ms
> 2016-11-09 23:50:27,408 INFO [main] Search lyrics on "Lyrster" [lyrster]...
> 2016-11-09 23:50:27,414 INFO [main] Found song info on "UtaMap" [utamap], 311.0 ms
> 2016-11-09 23:50:27,425 INFO [main] Search lyrics on "LyricsHuddle" [lyricshuddle]...
> 2016-11-09 23:50:27,442 INFO [main] Search lyrics on "eLyrics" [elyrics]...
> 2016-11-09 23:50:27,453 INFO [main] Search lyrics on "NitroLyrics" [nitrolyrics]...
> 2016-11-09 23:50:27,476 INFO [main] Search lyrics on "Lololyrics" [lololyrics]...
> 2016-11-09 23:50:27,482 INFO [main] Search lyrics on "Anime Lyrics" [animelyrics]...
> 2016-11-09 23:50:27,488 INFO [main] Search lyrics on "Lyrical Nonsense" [lyricalnonsense]...
> 2016-11-09 23:50:27,495 INFO [main] Search lyrics on "Lyrics N Music" [lyricsnmusic]...
> 2016-11-09 23:50:27,523 INFO [main] Search lyrics on "LetsSingIt" [letssingit]...
> 2016-11-09 23:50:27,539 INFO [main] Search lyrics on "LyricsReg.com" [lyricsreg]...
> 2016-11-09 23:50:27,551 INFO [main] Search lyrics on "SongLyrics.com" [songlyrics]...
> 2016-11-09 23:50:27,577 INFO [main] Search lyrics on "Genius" [genius]...
> 2016-11-09 23:50:27,607 INFO [main] Search lyrics on "Mp3Lyrics" [mp3lyrics]...
> 2016-11-09 23:50:27,625 INFO [main] Found song info on "LyricsMania" [lyricsmania], 108.6 ms
> 2016-11-09 23:50:27,640 INFO [main] Nothing was found on "LyricsHuddle" [lyricshuddle], 69.2 ms
> 2016-11-09 23:50:27,648 INFO [main] Found song info on "MetroLyrics" [metrolyrics], 125.4 ms
> 2016-11-09 23:50:27,648 INFO [main] Search lyrics on "Lyrics.com" [lyricscom]...
> 2016-11-09 23:50:27,660 INFO [main] Search lyrics on "SeekaLyric" [seekalyric]...
> 2016-11-09 23:50:27,673 INFO [main] Search lyrics on "AbsoluteLyrics" [absolutelyrics]...
> 2016-11-09 23:50:27,679 INFO [main] Search lyrics on "AliveLyrics" [alivelyrics]...
> 2016-11-09 23:50:27,702 INFO [main] Search lyrics on "AlLyrics.net" [allyrics]...
> 2016-11-09 23:50:27,718 INFO [main] Search lyrics on "Lyrics Action" [lyricsaction]...
> 2016-11-09 23:50:27,786 INFO [main] Search lyrics on "Evesta" [evesta]...
> 2016-11-09 23:50:27,802 INFO [main] Found song info on "LyricsReg.com" [lyricsreg], 83.5 ms
> 2016-11-09 23:50:27,816 INFO [main] Search lyrics on "LyricsMode" [lyricsmode]...
> 2016-11-09 23:50:27,835 ERROR [main] Failed to get info from "Amalgama" [amalgama]
> Traceback (most recent call last):
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/main.py", line 224, in do_search
>     song = plugin.search_song(artist, title)
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/plugin/amalgama.py", line 35, in search_song
>     song_artist = head_pane_parts[3].text
> IndexError: list index out of range
> 2016-11-09 23:50:27,835 INFO [main] Search lyrics on "Alphabet Lyrics" [alphabetlyrics]...
> 2016-11-09 23:50:27,853 INFO [main] Found song info on "SongLyrics.com" [songlyrics], 133.9 ms
> 2016-11-09 23:50:27,858 INFO [main] Search lyrics on "Directlyrics" [directlyrics]...
> 2016-11-09 23:50:27,876 INFO [main] Search lyrics on "Lyrics Depot" [lyricsdepot]...
> 2016-11-09 23:50:27,882 INFO [main] Search lyrics on "1 Song Lyrics" [1songlyrics]...
> 2016-11-09 23:50:27,910 INFO [main] Search lyrics on "Nautiljon" [nautiljon]...
> 2016-11-09 23:50:27,918 INFO [main] Found song info on "Genius" [genius], 131.5 ms
> 2016-11-09 23:50:27,929 INFO [main] Search lyrics on "Lyrics Place" [lyricsplace]...
> 2016-11-09 23:50:27,949 INFO [main] Found song info on "LetsSingIt" [letssingit], 239.7 ms
> 2016-11-09 23:50:27,949 INFO [main] Search lyrics on "1 Music Lyrics" [1musiclyrics]...
> 2016-11-09 23:50:27,955 INFO [main] Search lyrics on "Snakie's Obsession" [snakie]...
> 2016-11-09 23:50:27,987 INFO [main] Found song info on "AbsoluteLyrics" [absolutelyrics], 58.0 ms
> 2016-11-09 23:50:27,999 INFO [main] Found song info on "AliveLyrics" [alivelyrics], 57.3 ms
> 2016-11-09 23:50:28,003 INFO [main] Found song info on "SeekaLyric" [seekalyric], 92.4 ms
> 2016-11-09 23:50:28,003 INFO [main] Search lyrics on "JetLyrics" [jetlyrics]...
> 2016-11-09 23:50:28,032 INFO [main] Nothing was found on "Uta-Net" [utanet], 947.0 ms
> 2016-11-09 23:50:28,044 INFO [main] Search lyrics on "Lyrsense" [lyrsense]...
> 2016-11-09 23:50:28,056 INFO [main] Found song info on "AlLyrics.net" [allyrics], 108.4 ms
> 2016-11-09 23:50:28,095 INFO [main] Nothing was found on "Lyrics.com" [lyricscom], 190.4 ms
> 2016-11-09 23:50:28,099 INFO [main] Search lyrics on "LyricsFreak" [lyricsfreak]...
> 2016-11-09 23:50:28,101 INFO [main] Found song info on "Lyrics Action" [lyricsaction], 152.5 ms
> 2016-11-09 23:50:28,124 INFO [main] Found song info on "LyricsMode" [lyricsmode], 163.3 ms
> 2016-11-09 23:50:28,125 INFO [main] Search lyrics on "Lyrics.net" [lyricsnet]...
> 2016-11-09 23:50:28,130 INFO [main] Search lyrics on "Songs Lyrics" [songslyrics]...
> 2016-11-09 23:50:28,145 INFO [main] Found song info on "Evesta" [evesta], 190.0 ms
> 2016-11-09 23:50:28,145 INFO [main] Search lyrics on "Vagalume" [vagalume]...
> 2016-11-09 23:50:28,146 INFO [main] Search lyrics on "Letras" [letras]...
> 2016-11-09 23:50:28,146 INFO [main] Search lyrics on "Lyrics Bay" [lyricsbay]...
> 2016-11-09 23:50:28,147 INFO [main] Search lyrics on "Chartlyrics" [chartlyrics]...
> 2016-11-09 23:50:28,153 INFO [main] Search lyrics on "Song5" [song5]...
> 2016-11-09 23:50:28,186 INFO [main] Found song info on "Lyrics Depot" [lyricsdepot], 39.0 ms
> 2016-11-09 23:50:28,188 INFO [main] Found song info on "Alphabet Lyrics" [alphabetlyrics], 57.3 ms
> 2016-11-09 23:50:28,201 INFO [main] Found song info on "1 Song Lyrics" [1songlyrics], 54.3 ms
> 2016-11-09 23:50:28,216 INFO [main] Found song info on "Lyrics Place" [lyricsplace], 36.0 ms
> 2016-11-09 23:50:28,230 INFO [main] Nothing was found on "JetLyrics" [jetlyrics], 28.6 ms
> 2016-11-09 23:50:28,235 INFO [main] Found song info on "1 Music Lyrics" [1musiclyrics], 47.4 ms
> 2016-11-09 23:50:28,275 INFO [main] Found song info on "Vagalume" [vagalume], 38.0 ms
> 2016-11-09 23:50:28,279 INFO [main] Found song info on "LyricsFreak" [lyricsfreak], 43.2 ms
> 2016-11-09 23:50:28,280 INFO [main] Found song info on "Chartlyrics" [chartlyrics], 27.5 ms
> 2016-11-09 23:50:28,355 ERROR [main] Failed to get info from "Song5" [song5]
> Traceback (most recent call last):
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/main.py", line 224, in do_search
>     song = plugin.search_song(artist, title)
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/plugin/song5.py", line 33, in search_song
>     lyric = self.parse_verse_block(lyrics_pane, tags_to_skip=['ul', 'script', 'ins', 'a', 'div'])
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/plugin/common.py", line 187, in parse_verse_block
>     for elem in verse_block.childGenerator():
> AttributeError: 'NoneType' object has no attribute 'childGenerator'
> 2016-11-09 23:50:28,411 INFO [main] Nothing was found on "Lololyrics" [lololyrics], 756.4 ms
> 2016-11-09 23:50:28,509 INFO [main] Found song info on "Lyrics.net" [lyricsnet], 272.1 ms
> 2016-11-09 23:50:28,825 INFO [main] Nothing was found on "KashiNavi" [kashinavi], 1671.8 ms
> 2016-11-09 23:50:29,048 INFO [main] Nothing was found on "Snakie's Obsession" [snakie], 859.5 ms
> 2016-11-09 23:50:29,552 INFO [main] Nothing was found on "Nautiljon" [nautiljon], 1400.0 ms
> 2016-11-09 23:50:33,056 INFO [main] Nothing was found on "Anime Lyrics" [animelyrics], 5388.3 ms
> 2016-11-09 23:50:36,568 INFO [main] Nothing was found on "TouhouWiki" [touhouwiki], 9487.1 ms
> 2016-11-09 23:50:37,894 INFO [main] Nothing was found on "Mp3Lyrics" [mp3lyrics], 10047.7 ms
> 2016-11-09 23:50:38,114 INFO [main] Nothing was found on "NitroLyrics" [nitrolyrics], 10465.7 ms
> 2016-11-09 23:50:38,178 INFO [main] Nothing was found on "Directlyrics" [directlyrics], 10031.8 ms
> 2016-11-09 23:50:38,256 INFO [main] Nothing was found on "Songs Lyrics" [songslyrics], 10019.1 ms
> 2016-11-09 23:50:38,262 INFO [main] Nothing was found on "Lyrics Bay" [lyricsbay], 10010.3 ms
> 2016-11-09 23:50:38,728 INFO [main] Nothing was found on "KGet" [kget], 11646.4 ms
> 2016-11-09 23:50:39,066 INFO [main] Nothing was found on "Lyrical Nonsense" [lyricalnonsense], 11387.1 ms
> 2016-11-09 23:50:39,079 INFO [main] Nothing was found on "Lyrics N Music" [lyricsnmusic], 11382.5 ms
> 2016-11-09 23:50:40,359 INFO [main] Nothing was found on "eLyrics" [elyrics], 12710.6 ms
> 2016-11-09 23:50:43,699 INFO [main] Nothing was found on "Letras" [letras], 15456.3 ms
> 2016-11-09 23:50:46,118 INFO [main] Found song info on "LyricWiki" [lyricwiki], 18940.8 ms
> 2016-11-09 23:50:47,133 INFO [main] Nothing was found on "Lyrster" [lyrster], 19587.7 ms
> 2016-11-09 23:50:52,785 INFO [main] Found song info on "Lyrsense" [lyrsense], 24562.8 ms
> 2016-11-09 23:51:17,380 INFO [main] Nothing was found on "Sing365" [sing365], 50167.9 ms
> 2016-11-09 23:51:17,420 INFO [main] Nothing was found on "Kasi-Time" [kasitime], 50294.1 ms
> Traceback (most recent call last):
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/qt/controller.py", line 302, in run
>     item_songs = main.search(item[0], item[1], self.config)
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/main.py", line 170, in search
>     results = search_async(artist, title, config)
>   File "/Users/SID/Desktop/prismriver-lyrics-master/prismriver/main.py", line 203, in search_async
>     for items in range(0, queue.qsize()):
>   File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/multiprocessing/queues.py", line 117, in qsize
>     return self._maxsize - self._sem._semlock._get_value()
> NotImplementedError
> [1]    82643 abort      /Users/SID/Desktop/prismriver-lyrics-master/prismriver-gui.py

**Comment by anlar** [comment]
Alright, there is a difference on OS X - `sem_getvalue()` is not implemented here: https://docs.python.org/3.5/library/multiprocessing.html#multiprocessing.Queue.qsize

Please try latest version with fix (also you can launch app in single-thread mode with `--sync` option, but that will work slower).

Hopefully, that should be the last iteration :)

**Comment by AlickH** [comment]
Finally it works perfectly. Thanks Very much!
![pic](https://i.imgur.com/wx534Cl.png)

And there is one more question
if I can get title and artist from iTunes automatically
I can get these information by AppleScript or bash

> ARTIST=`osascript -e'tell application "iTunes"' -e'get artist of current track' -e'end tell'`
>   TITLE=`osascript -e'tell application "iTunes"' -e'get name of current track' -e'end tell'`
> ALBUM=`osascript -e'tell application "iTunes"' -e'get album of current track' -e'end tell'`

but I don't know how to insert them into the UI windows.

**Comment by anlar** [comment]
Default implementation is using mpris to listen to player. If you want something different you'll need to re-write `mpris.py` for your case. E.g here is version that loading song from deadbeef:

```
import subprocess


class MprisConnector(object):
    def __init__(self):
        super().__init__()

    def get_players(self):
        return [MprisPlayer("shell", "DeaDBeeF")]

    def connect(self, player):
        return True

    def get_meta(self):
        try:
            return [[subprocess.check_output("/opt/deadbeef/bin/deadbeef --nowplaying %a", shell=True).decode('utf-8'),
                     subprocess.check_output("/opt/deadbeef/bin/deadbeef --nowplaying %t", shell=True).decode('utf-8')]]
        except subprocess.CalledProcessError:
            return None


def get_player_icon_path(player_name):
    player_icons = {'org.mpris.MediaPlayer2.amarok': 'amarok.png',
                    'org.mpris.MediaPlayer2.audacious': 'audacious.png',
                    'org.mpris.MediaPlayer2.deadbeef': 'deadbeef.png',
                    'org.mpris.MediaPlayer2.mpd': 'mpd.png',
                    'org.mpris.MediaPlayer2.rhythmbox': 'rhythmbox.png',
                    'org.mpris.MediaPlayer2.vlc': 'vlc.png'}

    return 'prismriver/pixmaps/player/' + player_icons.get(player_name, 'default.png')


class MprisPlayer(object):
    def __init__(self, name, identity):
        super().__init__()

        self.name = name
        self.identity = identity

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__


class MprisConnectionException(Exception):
    pass
```

Probably that should work for you if you replace calls to deadbeef with your scripts.

**Comment by AlickH** [comment]
Thanks very much for your help!
I modified it as 

```
import re
import subprocess
import dbus
import os


class MprisConnector(object):
    def __init__(self):
        super().__init__()

    def get_players(self):
        return [MprisPlayer("Mac","iTunes")]

    def connect(self, player):
        return True

    def get_meta(self):
        try:
            return [[subprocess.check_output('''osascript -e 'tell application "iTunes" to artist of current track as string' %a''', shell=True).decode('utf-8'),
                     subprocess.check_output('''osascript -e 'tell application "iTunes" to name of current track as string' %t''', shell=True).decode('utf-8')]]
        except subprocess.CalledProcessError:
            return None




class MprisPlayer(object):
    def __init__(self, name, identity):
        super().__init__()

        self.name = name
        self.identity = identity

    def __eq__(self, other):
        return isinstance(other, self.__class__) and self.__dict__ == other.__dict__


class MprisConnectionException(Exception):
    pass
```

so it can grab info from iTunes automatically
and with the change of relevant path of items in **controller.py**

```
import os

path = os.path.dirname(os.path.abspath(__file__))


class MainController(object):
    def __init__(self, config, default_artist, default_title, default_player, connect_to_player):
        super().__init__()

        self.config = config

        self.mpris_connect = MprisConnector()
        self.worker_search = None
        self.worker_mpris = None
        self.mpris_player = None

        self.main_window = None


        self.start_app(default_artist, default_title, default_player, connect_to_player)

    def start_app(self, default_artist, default_title, default_player, connect_to_player):
        app = QApplication(sys.argv)
        app.setWindowIcon(QIcon(os.path.join(path, 'prismriver.png')))
```

 and **window.py**

```
import os

path = os.path.dirname(os.path.abspath(__file__))

class MainWindow(QMainWindow):
    def __init__(self):
        QMainWindow.__init__(self)
        uic.loadUi(os.path.join(path, 'window.ui'), self)
```

Now I can open it regardless of the path
I make it to be an AlfredWorkflow so that I can open it with shortcut
and it works perfectly
![Imgur](http://i.imgur.com/KZYFhtj.png)
Thanks for your EXCELLENT work again!!! 😘

**Comment by anlar** [comment]
Thanks, I've added fix with absolute path for resource loading.
